//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  ingredientes: Ingredientes;
  ingredientesConnection: IngredientesConnection;
  propiedades: Propiedades;
  propiedadesConnection: PropiedadesConnection;
  shop: Shop;
  shopConnection: ShopConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryIngredientesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIngredientesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IngredientesFilter>;
};


export type QueryPropiedadesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPropiedadesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PropiedadesFilter>;
};


export type QueryShopArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryShopConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShopFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  ingredientes?: InputMaybe<IngredientesFilter>;
  propiedades?: InputMaybe<PropiedadesFilter>;
  shop?: InputMaybe<ShopFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Ingredientes | Propiedades | Shop | Folder;

export type HomeHero = {
  __typename?: 'HomeHero';
  headline?: Maybe<Scalars['String']['output']>;
  subheadline?: Maybe<Scalars['String']['output']>;
};

export type HomeTechnical = {
  __typename?: 'HomeTechnical';
  heading?: Maybe<Scalars['String']['output']>;
  body1?: Maybe<Scalars['String']['output']>;
  body2?: Maybe<Scalars['String']['output']>;
};

export type HomeProductosItems = {
  __typename?: 'HomeProductosItems';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
};

export type HomeProductos = {
  __typename?: 'HomeProductos';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeProductosItems>>>;
};

export type HomePorQueFeatures = {
  __typename?: 'HomePorQueFeatures';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HomePorQue = {
  __typename?: 'HomePorQue';
  heading?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<HomePorQueFeatures>>>;
};

export type HomeRitual = {
  __typename?: 'HomeRitual';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeContacto = {
  __typename?: 'HomeContacto';
  heading?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  technical?: Maybe<HomeTechnical>;
  productos?: Maybe<HomeProductos>;
  porQue?: Maybe<HomePorQue>;
  ritual?: Maybe<HomeRitual>;
  contacto?: Maybe<HomeContacto>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHeroFilter = {
  headline?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
};

export type HomeTechnicalFilter = {
  heading?: InputMaybe<StringFilter>;
  body1?: InputMaybe<StringFilter>;
  body2?: InputMaybe<StringFilter>;
};

export type HomeProductosItemsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
};

export type HomeProductosFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomeProductosItemsFilter>;
};

export type HomePorQueFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomePorQueFilter = {
  heading?: InputMaybe<StringFilter>;
  features?: InputMaybe<HomePorQueFeaturesFilter>;
};

export type HomeRitualFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeContactoFilter = {
  heading?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  technical?: InputMaybe<HomeTechnicalFilter>;
  productos?: InputMaybe<HomeProductosFilter>;
  porQue?: InputMaybe<HomePorQueFilter>;
  ritual?: InputMaybe<HomeRitualFilter>;
  contacto?: InputMaybe<HomeContactoFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type IngredientesIngredientsList = {
  __typename?: 'IngredientesIngredientsList';
  image?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Ingredientes = Node & Document & {
  __typename?: 'Ingredientes';
  heading?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  ingredientsTitle?: Maybe<Scalars['String']['output']>;
  ingredientsList?: Maybe<Array<Maybe<IngredientesIngredientsList>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type IngredientesIngredientsListFilter = {
  image?: InputMaybe<ImageFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type IngredientesFilter = {
  heading?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  ingredientsTitle?: InputMaybe<StringFilter>;
  ingredientsList?: InputMaybe<IngredientesIngredientsListFilter>;
};

export type IngredientesConnectionEdges = {
  __typename?: 'IngredientesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Ingredientes>;
};

export type IngredientesConnection = Connection & {
  __typename?: 'IngredientesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IngredientesConnectionEdges>>>;
};

export type PropiedadesPropertiesReferences = {
  __typename?: 'PropiedadesPropertiesReferences';
  citation?: Maybe<Scalars['String']['output']>;
};

export type PropiedadesProperties = {
  __typename?: 'PropiedadesProperties';
  title?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['JSON']['output']>;
  references?: Maybe<Array<Maybe<PropiedadesPropertiesReferences>>>;
};

export type Propiedades = Node & Document & {
  __typename?: 'Propiedades';
  heading?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  properties?: Maybe<Array<Maybe<PropiedadesProperties>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PropiedadesPropertiesReferencesFilter = {
  citation?: InputMaybe<StringFilter>;
};

export type PropiedadesPropertiesFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  content?: InputMaybe<RichTextFilter>;
  references?: InputMaybe<PropiedadesPropertiesReferencesFilter>;
};

export type PropiedadesFilter = {
  heading?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  properties?: InputMaybe<PropiedadesPropertiesFilter>;
};

export type PropiedadesConnectionEdges = {
  __typename?: 'PropiedadesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Propiedades>;
};

export type PropiedadesConnection = Connection & {
  __typename?: 'PropiedadesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PropiedadesConnectionEdges>>>;
};

export type Shop = Node & Document & {
  __typename?: 'Shop';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  secondaryText?: Maybe<Scalars['String']['output']>;
  minimumOrder?: Maybe<Scalars['String']['output']>;
  note?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ShopFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  secondaryText?: InputMaybe<StringFilter>;
  minimumOrder?: InputMaybe<StringFilter>;
  note?: InputMaybe<StringFilter>;
};

export type ShopConnectionEdges = {
  __typename?: 'ShopConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Shop>;
};

export type ShopConnection = Connection & {
  __typename?: 'ShopConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ShopConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateIngredientes: Ingredientes;
  createIngredientes: Ingredientes;
  updatePropiedades: Propiedades;
  createPropiedades: Propiedades;
  updateShop: Shop;
  createShop: Shop;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateIngredientesArgs = {
  relativePath: Scalars['String']['input'];
  params: IngredientesMutation;
};


export type MutationCreateIngredientesArgs = {
  relativePath: Scalars['String']['input'];
  params: IngredientesMutation;
};


export type MutationUpdatePropiedadesArgs = {
  relativePath: Scalars['String']['input'];
  params: PropiedadesMutation;
};


export type MutationCreatePropiedadesArgs = {
  relativePath: Scalars['String']['input'];
  params: PropiedadesMutation;
};


export type MutationUpdateShopArgs = {
  relativePath: Scalars['String']['input'];
  params: ShopMutation;
};


export type MutationCreateShopArgs = {
  relativePath: Scalars['String']['input'];
  params: ShopMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  ingredientes?: InputMaybe<IngredientesMutation>;
  propiedades?: InputMaybe<PropiedadesMutation>;
  shop?: InputMaybe<ShopMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  ingredientes?: InputMaybe<IngredientesMutation>;
  propiedades?: InputMaybe<PropiedadesMutation>;
  shop?: InputMaybe<ShopMutation>;
};

export type HomeHeroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
};

export type HomeTechnicalMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body1?: InputMaybe<Scalars['String']['input']>;
  body2?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProductosItemsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProductosMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeProductosItemsMutation>>>;
};

export type HomePorQueFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomePorQueMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<HomePorQueFeaturesMutation>>>;
};

export type HomeRitualMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeContactoMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  technical?: InputMaybe<HomeTechnicalMutation>;
  productos?: InputMaybe<HomeProductosMutation>;
  porQue?: InputMaybe<HomePorQueMutation>;
  ritual?: InputMaybe<HomeRitualMutation>;
  contacto?: InputMaybe<HomeContactoMutation>;
};

export type IngredientesIngredientsListMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type IngredientesMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  ingredientsTitle?: InputMaybe<Scalars['String']['input']>;
  ingredientsList?: InputMaybe<Array<InputMaybe<IngredientesIngredientsListMutation>>>;
};

export type PropiedadesPropertiesReferencesMutation = {
  citation?: InputMaybe<Scalars['String']['input']>;
};

export type PropiedadesPropertiesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['JSON']['input']>;
  references?: InputMaybe<Array<InputMaybe<PropiedadesPropertiesReferencesMutation>>>;
};

export type PropiedadesMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  properties?: InputMaybe<Array<InputMaybe<PropiedadesPropertiesMutation>>>;
};

export type ShopMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  secondaryText?: InputMaybe<Scalars['String']['input']>;
  minimumOrder?: InputMaybe<Scalars['String']['input']>;
  note?: InputMaybe<Scalars['String']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', headline?: string | null, subheadline?: string | null } | null, technical?: { __typename: 'HomeTechnical', heading?: string | null, body1?: string | null, body2?: string | null } | null, productos?: { __typename: 'HomeProductos', heading?: string | null, items?: Array<{ __typename: 'HomeProductosItems', name?: string | null, description?: string | null, details?: string | null } | null> | null } | null, porQue?: { __typename: 'HomePorQue', heading?: string | null, features?: Array<{ __typename: 'HomePorQueFeatures', title?: string | null, description?: string | null } | null> | null } | null, ritual?: { __typename: 'HomeRitual', heading?: string | null, body?: string | null } | null, contacto?: { __typename: 'HomeContacto', heading?: string | null } | null };

export type IngredientesPartsFragment = { __typename: 'Ingredientes', heading?: string | null, intro?: string | null, ingredientsTitle?: string | null, ingredientsList?: Array<{ __typename: 'IngredientesIngredientsList', image?: string | null, name?: string | null, description?: string | null } | null> | null };

export type PropiedadesPartsFragment = { __typename: 'Propiedades', heading?: string | null, intro?: string | null, properties?: Array<{ __typename: 'PropiedadesProperties', title?: string | null, slug?: string | null, description?: string | null, image?: string | null, content?: any | null, references?: Array<{ __typename: 'PropiedadesPropertiesReferences', citation?: string | null } | null> | null } | null> | null };

export type ShopPartsFragment = { __typename: 'Shop', heading?: string | null, body?: string | null, ctaText?: string | null, secondaryText?: string | null, minimumOrder?: string | null, note?: string | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', headline?: string | null, subheadline?: string | null } | null, technical?: { __typename: 'HomeTechnical', heading?: string | null, body1?: string | null, body2?: string | null } | null, productos?: { __typename: 'HomeProductos', heading?: string | null, items?: Array<{ __typename: 'HomeProductosItems', name?: string | null, description?: string | null, details?: string | null } | null> | null } | null, porQue?: { __typename: 'HomePorQue', heading?: string | null, features?: Array<{ __typename: 'HomePorQueFeatures', title?: string | null, description?: string | null } | null> | null } | null, ritual?: { __typename: 'HomeRitual', heading?: string | null, body?: string | null } | null, contacto?: { __typename: 'HomeContacto', heading?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', headline?: string | null, subheadline?: string | null } | null, technical?: { __typename: 'HomeTechnical', heading?: string | null, body1?: string | null, body2?: string | null } | null, productos?: { __typename: 'HomeProductos', heading?: string | null, items?: Array<{ __typename: 'HomeProductosItems', name?: string | null, description?: string | null, details?: string | null } | null> | null } | null, porQue?: { __typename: 'HomePorQue', heading?: string | null, features?: Array<{ __typename: 'HomePorQueFeatures', title?: string | null, description?: string | null } | null> | null } | null, ritual?: { __typename: 'HomeRitual', heading?: string | null, body?: string | null } | null, contacto?: { __typename: 'HomeContacto', heading?: string | null } | null } | null } | null> | null } };

export type IngredientesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IngredientesQuery = { __typename?: 'Query', ingredientes: { __typename: 'Ingredientes', id: string, heading?: string | null, intro?: string | null, ingredientsTitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, ingredientsList?: Array<{ __typename: 'IngredientesIngredientsList', image?: string | null, name?: string | null, description?: string | null } | null> | null } };

export type IngredientesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IngredientesFilter>;
}>;


export type IngredientesConnectionQuery = { __typename?: 'Query', ingredientesConnection: { __typename?: 'IngredientesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IngredientesConnectionEdges', cursor: string, node?: { __typename: 'Ingredientes', id: string, heading?: string | null, intro?: string | null, ingredientsTitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, ingredientsList?: Array<{ __typename: 'IngredientesIngredientsList', image?: string | null, name?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type PropiedadesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PropiedadesQuery = { __typename?: 'Query', propiedades: { __typename: 'Propiedades', id: string, heading?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, properties?: Array<{ __typename: 'PropiedadesProperties', title?: string | null, slug?: string | null, description?: string | null, image?: string | null, content?: any | null, references?: Array<{ __typename: 'PropiedadesPropertiesReferences', citation?: string | null } | null> | null } | null> | null } };

export type PropiedadesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PropiedadesFilter>;
}>;


export type PropiedadesConnectionQuery = { __typename?: 'Query', propiedadesConnection: { __typename?: 'PropiedadesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PropiedadesConnectionEdges', cursor: string, node?: { __typename: 'Propiedades', id: string, heading?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, properties?: Array<{ __typename: 'PropiedadesProperties', title?: string | null, slug?: string | null, description?: string | null, image?: string | null, content?: any | null, references?: Array<{ __typename: 'PropiedadesPropertiesReferences', citation?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type ShopQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ShopQuery = { __typename?: 'Query', shop: { __typename: 'Shop', id: string, heading?: string | null, body?: string | null, ctaText?: string | null, secondaryText?: string | null, minimumOrder?: string | null, note?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ShopConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShopFilter>;
}>;


export type ShopConnectionQuery = { __typename?: 'Query', shopConnection: { __typename?: 'ShopConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ShopConnectionEdges', cursor: string, node?: { __typename: 'Shop', id: string, heading?: string | null, body?: string | null, ctaText?: string | null, secondaryText?: string | null, minimumOrder?: string | null, note?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    headline
    subheadline
  }
  technical {
    __typename
    heading
    body1
    body2
  }
  productos {
    __typename
    heading
    items {
      __typename
      name
      description
      details
    }
  }
  porQue {
    __typename
    heading
    features {
      __typename
      title
      description
    }
  }
  ritual {
    __typename
    heading
    body
  }
  contacto {
    __typename
    heading
  }
}
    `;
export const IngredientesPartsFragmentDoc = gql`
    fragment IngredientesParts on Ingredientes {
  __typename
  heading
  intro
  ingredientsTitle
  ingredientsList {
    __typename
    image
    name
    description
  }
}
    `;
export const PropiedadesPartsFragmentDoc = gql`
    fragment PropiedadesParts on Propiedades {
  __typename
  heading
  intro
  properties {
    __typename
    title
    slug
    description
    image
    content
    references {
      __typename
      citation
    }
  }
}
    `;
export const ShopPartsFragmentDoc = gql`
    fragment ShopParts on Shop {
  __typename
  heading
  body
  ctaText
  secondaryText
  minimumOrder
  note
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const IngredientesDocument = gql`
    query ingredientes($relativePath: String!) {
  ingredientes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IngredientesParts
  }
}
    ${IngredientesPartsFragmentDoc}`;
export const IngredientesConnectionDocument = gql`
    query ingredientesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IngredientesFilter) {
  ingredientesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IngredientesParts
      }
    }
  }
}
    ${IngredientesPartsFragmentDoc}`;
export const PropiedadesDocument = gql`
    query propiedades($relativePath: String!) {
  propiedades(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PropiedadesParts
  }
}
    ${PropiedadesPartsFragmentDoc}`;
export const PropiedadesConnectionDocument = gql`
    query propiedadesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PropiedadesFilter) {
  propiedadesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PropiedadesParts
      }
    }
  }
}
    ${PropiedadesPartsFragmentDoc}`;
export const ShopDocument = gql`
    query shop($relativePath: String!) {
  shop(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ShopParts
  }
}
    ${ShopPartsFragmentDoc}`;
export const ShopConnectionDocument = gql`
    query shopConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ShopFilter) {
  shopConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ShopParts
      }
    }
  }
}
    ${ShopPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    ingredientes(variables: IngredientesQueryVariables, options?: C): Promise<{data: IngredientesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IngredientesQueryVariables, query: string}> {
        return requester<{data: IngredientesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IngredientesQueryVariables, query: string}, IngredientesQueryVariables>(IngredientesDocument, variables, options);
      },
    ingredientesConnection(variables?: IngredientesConnectionQueryVariables, options?: C): Promise<{data: IngredientesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IngredientesConnectionQueryVariables, query: string}> {
        return requester<{data: IngredientesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IngredientesConnectionQueryVariables, query: string}, IngredientesConnectionQueryVariables>(IngredientesConnectionDocument, variables, options);
      },
    propiedades(variables: PropiedadesQueryVariables, options?: C): Promise<{data: PropiedadesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PropiedadesQueryVariables, query: string}> {
        return requester<{data: PropiedadesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PropiedadesQueryVariables, query: string}, PropiedadesQueryVariables>(PropiedadesDocument, variables, options);
      },
    propiedadesConnection(variables?: PropiedadesConnectionQueryVariables, options?: C): Promise<{data: PropiedadesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PropiedadesConnectionQueryVariables, query: string}> {
        return requester<{data: PropiedadesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PropiedadesConnectionQueryVariables, query: string}, PropiedadesConnectionQueryVariables>(PropiedadesConnectionDocument, variables, options);
      },
    shop(variables: ShopQueryVariables, options?: C): Promise<{data: ShopQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopQueryVariables, query: string}> {
        return requester<{data: ShopQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopQueryVariables, query: string}, ShopQueryVariables>(ShopDocument, variables, options);
      },
    shopConnection(variables?: ShopConnectionQueryVariables, options?: C): Promise<{data: ShopConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopConnectionQueryVariables, query: string}> {
        return requester<{data: ShopConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopConnectionQueryVariables, query: string}, ShopConnectionQueryVariables>(ShopConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  